# Generated by Django 6.0.5 on 2026-06-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкция')),
                ('answer_type', models.CharField(
                    choices=[
                        ('yes_no', 'Да / Нет'),
                        ('frequency_4', 'Частота (4 варианта)'),
                        ('agree_4', 'Согласие (4 варианта)'),
                        ('cia_likert', 'Интенсивность (4 варианта)'),
                        ('bes_likert', 'Дискомфорт (4 варианта)'),
                        ('psqi_likert', 'Частота за месяц (4 варианта)'),
                    ],
                    default='yes_no',
                    max_length=32,
                    verbose_name='Тип ответов',
                )),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='custom_tests',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор',
                )),
            ],
            options={
                'verbose_name': 'Собственный тест',
                'verbose_name_plural': 'Собственные тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('test', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='questions',
                    to='pages.customtest',
                    verbose_name='Тест',
                )),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
