# Generated by Django 6.0.5 on 2026-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='moderation_note',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
