# Generated by Django 6.0.5 on 2026-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_psychologistprofile_moderated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistprofile',
            name='moderation_note',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий модератора'),
        ),
    ]
